---
- name: Backup Aruba CX Switch Config to Windows Server
  hosts: aruba_switches
  gather_facts: yes
  collections:
    - arubanetworks.aoscx
    - ansible.netcommon
    - ansible.windows

  vars:
    backup_path: "D:\\Switch_logs"

  tasks:
    - name: Get running configuration from Aruba CX
      arubanetworks.aoscx.aoscx_command:
        commands:
          - show running-config
      register: switch_config

    - name: Ensure backup folder exists on Windows
      ansible.windows.win_file:
        path: "{{ backup_path }}"
        state: directory
      delegate_to: winserver01

    - name: Save configuration directly to Windows
      ansible.windows.win_copy:
        content: "{{ switch_config.stdout[0] }}"
        dest: "{{ backup_path }}\\{{ inventory_hostname }}_backup_{{ ansible_date_time.iso8601_basic }}.cfg"
      delegate_to: winserver01
