---
- name: Backup Aruba CX Switch Config to Windows Server
  hosts: aruba_switches
  gather_facts: no
  collections:
    - arubanetworks.aoscx
    - ansible.netcommon
    - ansible.windows

  vars:
    backup_path: "D:\\Switch_logs"

  tasks:

    - name: Get running configuration from Aruba CX
      aoscx_command:
        commands:
          - show running-config
      register: switch_config

    - name: Ensure backup folder exists on Windows
      win_file:
        path: "{{ backup_path }}"
        state: directory
      delegate_to: winserver01

    - name: Save configuration directly to Windows
      win_copy:
        content: "{{ switch_config.stdout[0] }}"
        dest: "{{ backup_path }}\\{{ inventory_hostname }}_backup_{{ lookup('pipe','date +%Y-%m-%d_%H-%M') }}.cfg"
      delegate_to: winserver01
